// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9mcf26H-5lEORJew8oxqCOlRKSoLgTTA',
    appId: '1:1011197581225:web:54b02e66cacaaa484496b8',
    messagingSenderId: '1011197581225',
    projectId: 'resto-a6a06',
    authDomain: 'resto-a6a06.firebaseapp.com',
    storageBucket: 'resto-a6a06.appspot.com',
    measurementId: 'G-NY8ELHBYQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-26dK2fHObWrmh_jMP-aco3JDT5pFkTw',
    appId: '1:1011197581225:android:40ac1fb5a4737b9d4496b8',
    messagingSenderId: '1011197581225',
    projectId: 'resto-a6a06',
    storageBucket: 'resto-a6a06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA9s9Zg_fUQ4MdaeeoesbX4HvC_ZI2smE',
    appId: '1:1011197581225:ios:01f4834ee39c81984496b8',
    messagingSenderId: '1011197581225',
    projectId: 'resto-a6a06',
    storageBucket: 'resto-a6a06.appspot.com',
    iosClientId: '1011197581225-qphc7hbd74qtnabpricm5drvf6sjplam.apps.googleusercontent.com',
    iosBundleId: 'com.example.tryriverpod',
  );
}
